// AUTO-GENERATED — do not edit.
// Regenerate with: bun run generate:graphql
/* eslint-disable */

export const CREATE_TRANSACTION = "mutation CreateTransaction($itemId: ID!, $accountId: ID!, $input: CreateTransactionInput!) {\n  createTransaction(itemId: $itemId, accountId: $accountId, input: $input) {\n    __typename\n    ...TransactionFields\n  }\n}\n\nfragment TagFields on Tag {\n  __typename\n  colorName\n  name\n  id\n}\n\nfragment GoalFields on Goal {\n  __typename\n  name\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  id\n}\n\nfragment TransactionFields on Transaction {\n  __typename\n  suggestedCategoryIds\n  recurringId\n  categoryId\n  isReviewed\n  accountId\n  createdAt\n  isPending\n  tipAmount\n  userNotes\n  itemId\n  amount\n  date\n  name\n  type\n  id\n  tags {\n    __typename\n    ...TagFields\n  }\n  goal {\n    __typename\n    ...GoalFields\n  }\n}";

export const EDIT_TRANSACTION = "mutation EditTransaction($itemId: ID!, $accountId: ID!, $id: ID!, $input: EditTransactionInput) {\n  editTransaction(itemId: $itemId, accountId: $accountId, id: $id, input: $input) {\n    __typename\n    transaction {\n      __typename\n      ...TransactionFields\n    }\n  }\n}\n\nfragment TagFields on Tag {\n  __typename\n  colorName\n  name\n  id\n}\n\nfragment GoalFields on Goal {\n  __typename\n  name\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  id\n}\n\nfragment TransactionFields on Transaction {\n  __typename\n  suggestedCategoryIds\n  recurringId\n  categoryId\n  isReviewed\n  accountId\n  createdAt\n  isPending\n  tipAmount\n  userNotes\n  itemId\n  amount\n  date\n  name\n  type\n  id\n  tags {\n    __typename\n    ...TagFields\n  }\n  goal {\n    __typename\n    ...GoalFields\n  }\n}";

export const DELETE_TRANSACTION = "mutation DeleteTransaction($itemId: ID!, $accountId: ID!, $id: ID!) {\n  deleteTransaction(itemId: $itemId, accountId: $accountId, id: $id)\n}";

export const ADD_TRANSACTION_TO_RECURRING = "mutation AddTransactionToRecurring($itemId: ID!, $accountId: ID!, $id: ID!, $input: AddTransactionToRecurringInput!) {\n  addTransactionToRecurring(\n    itemId: $itemId\n    accountId: $accountId\n    id: $id\n    input: $input\n  ) {\n    __typename\n    transaction {\n      __typename\n      ...TransactionFields\n    }\n  }\n}\n\nfragment TagFields on Tag {\n  __typename\n  colorName\n  name\n  id\n}\n\nfragment GoalFields on Goal {\n  __typename\n  name\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  id\n}\n\nfragment TransactionFields on Transaction {\n  __typename\n  suggestedCategoryIds\n  recurringId\n  categoryId\n  isReviewed\n  accountId\n  createdAt\n  isPending\n  tipAmount\n  userNotes\n  itemId\n  amount\n  date\n  name\n  type\n  id\n  tags {\n    __typename\n    ...TagFields\n  }\n  goal {\n    __typename\n    ...GoalFields\n  }\n}";

export const SPLIT_TRANSACTION = "mutation SplitTransaction($itemId: ID!, $accountId: ID!, $id: ID!, $input: [SplitTransactionInput!]!) {\n  splitTransaction(itemId: $itemId, accountId: $accountId, id: $id, input: $input) {\n    __typename\n    parentTransaction {\n      __typename\n      ...TransactionFields\n    }\n    splitTransactions {\n      __typename\n      ...TransactionFields\n    }\n  }\n}\n\nfragment TagFields on Tag {\n  __typename\n  colorName\n  name\n  id\n}\n\nfragment GoalFields on Goal {\n  __typename\n  name\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  id\n}\n\nfragment TransactionFields on Transaction {\n  __typename\n  suggestedCategoryIds\n  recurringId\n  categoryId\n  isReviewed\n  accountId\n  createdAt\n  isPending\n  tipAmount\n  userNotes\n  itemId\n  amount\n  date\n  name\n  type\n  id\n  tags {\n    __typename\n    ...TagFields\n  }\n  goal {\n    __typename\n    ...GoalFields\n  }\n}";

export const CREATE_CATEGORY = "mutation CreateCategory($input: CreateCategoryInput!, $spend: Boolean = false, $budget: Boolean = false) {\n  createCategory(input: $input) {\n    __typename\n    ...CategoryFields\n    spend @include(if: $spend) {\n      __typename\n      ...SpendFields\n    }\n    budget @include(if: $budget) {\n      __typename\n      ...BudgetFields\n    }\n    childCategories {\n      __typename\n      ...CategoryFields\n      spend @include(if: $spend) {\n        __typename\n        ...SpendFields\n      }\n      budget @include(if: $budget) {\n        __typename\n        ...BudgetFields\n      }\n    }\n  }\n}\n\nfragment SpendMonthlyFields on CategoryMonthlySpent {\n  __typename\n  unpaidRecurringAmount\n  paidRecurringAmount\n  comparisonAmount\n  amount\n  month\n  id\n}\n\nfragment BudgetMonthlyFields on CategoryMonthlyBudget {\n  __typename\n  unassignedRolloverAmount\n  childRolloverAmount\n  unassignedAmount\n  resolvedAmount\n  rolloverAmount\n  childAmount\n  goalAmount\n  amount\n  month\n  id\n}\n\nfragment CategoryFields on Category {\n  __typename\n  isRolloverDisabled\n  canBeDeleted\n  isExcluded\n  templateId\n  colorName\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  name\n  id\n}\n\nfragment SpendFields on CategorySpend {\n  __typename\n  current {\n    __typename\n    ...SpendMonthlyFields\n  }\n  histories {\n    __typename\n    ...SpendMonthlyFields\n  }\n}\n\nfragment BudgetFields on CategoryBudget {\n  __typename\n  current {\n    __typename\n    ...BudgetMonthlyFields\n  }\n  histories {\n    __typename\n    ...BudgetMonthlyFields\n  }\n}";

export const EDIT_CATEGORY = "mutation EditCategory($id: ID!, $input: EditCategoryInput!, $spend: Boolean = false, $budget: Boolean = false, $rollovers: Boolean = false) {\n  editCategory(id: $id, input: $input) {\n    __typename\n    category {\n      __typename\n      ...CategoryFields\n      spend @include(if: $spend) {\n        __typename\n        ...SpendFields\n      }\n      budget(isRolloverEnabled: $rollovers) @include(if: $budget) {\n        __typename\n        ...BudgetFields\n      }\n    }\n  }\n}\n\nfragment SpendMonthlyFields on CategoryMonthlySpent {\n  __typename\n  unpaidRecurringAmount\n  paidRecurringAmount\n  comparisonAmount\n  amount\n  month\n  id\n}\n\nfragment BudgetMonthlyFields on CategoryMonthlyBudget {\n  __typename\n  unassignedRolloverAmount\n  childRolloverAmount\n  unassignedAmount\n  resolvedAmount\n  rolloverAmount\n  childAmount\n  goalAmount\n  amount\n  month\n  id\n}\n\nfragment CategoryFields on Category {\n  __typename\n  isRolloverDisabled\n  canBeDeleted\n  isExcluded\n  templateId\n  colorName\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  name\n  id\n}\n\nfragment SpendFields on CategorySpend {\n  __typename\n  current {\n    __typename\n    ...SpendMonthlyFields\n  }\n  histories {\n    __typename\n    ...SpendMonthlyFields\n  }\n}\n\nfragment BudgetFields on CategoryBudget {\n  __typename\n  current {\n    __typename\n    ...BudgetMonthlyFields\n  }\n  histories {\n    __typename\n    ...BudgetMonthlyFields\n  }\n}";

export const DELETE_CATEGORY = "mutation DeleteCategory($id: ID!) {\n  deleteCategory(id: $id)\n}";

export const CREATE_TAG = "mutation CreateTag($input: CreateTagInput!) {\n  createTag(input: $input) {\n    __typename\n    ...TagFields\n  }\n}\n\nfragment TagFields on Tag {\n  __typename\n  colorName\n  name\n  id\n}";

export const EDIT_TAG = "mutation EditTag($id: ID!, $input: EditTagInput!) {\n  editTag(id: $id, input: $input) {\n    __typename\n    ...TagFields\n  }\n}\n\nfragment TagFields on Tag {\n  __typename\n  colorName\n  name\n  id\n}";

export const DELETE_TAG = "mutation DeleteTag($id: ID!) {\n  deleteTag(id: $id)\n}";

export const CREATE_RECURRING = "mutation CreateRecurring($input: CreateRecurringInput!) {\n  createRecurring(input: $input) {\n    __typename\n    ...RecurringFields\n  }\n}\n\nfragment RecurringFields on Recurring {\n  __typename\n  nextPaymentAmount\n  nextPaymentDate\n  categoryId\n  frequency\n  emoji\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  state\n  name\n  id\n}";

export const EDIT_RECURRING = "mutation EditRecurring($id: ID!, $input: EditRecurringInput!) {\n  editRecurring(id: $id, input: $input) {\n    __typename\n    recurring {\n      __typename\n      ...RecurringFields\n    }\n  }\n}\n\nfragment RecurringFields on Recurring {\n  __typename\n  nextPaymentAmount\n  nextPaymentDate\n  categoryId\n  frequency\n  emoji\n  icon {\n    __typename\n    ... on EmojiUnicode {\n      __typename\n      unicode\n    }\n    ... on Genmoji {\n      __typename\n      id\n      src\n    }\n  }\n  state\n  name\n  id\n}";

export const DELETE_RECURRING = "mutation DeleteRecurring($deleteRecurringId: ID!) {\n  deleteRecurring(id: $deleteRecurringId)\n}";

export const EDIT_BUDGET = "mutation EditBudget($categoryId: ID!, $input: EditCategoryBudgetInput!) {\n  editCategoryBudget(categoryId: $categoryId, input: $input)\n}";

export const EDIT_BUDGET_MONTHLY = "mutation EditBudgetMonthly($categoryId: ID!, $input: [EditCategoryBudgetMonthlyInput!]!) {\n  editCategoryBudgetMonthly(categoryId: $categoryId, input: $input)\n}";

export const EDIT_ACCOUNT = "mutation EditAccount($itemId: ID!, $id: ID!, $input: EditAccountInput!) {\n  editAccount(itemId: $itemId, id: $id, input: $input) {\n    __typename\n    account {\n      __typename\n      ...AccountFields\n    }\n  }\n}\n\nfragment AccountFields on Account {\n  __typename\n  hasHistoricalUpdates\n  latestBalanceUpdate\n  hasLiveBalance\n  institutionId\n  isUserHidden\n  isUserClosed\n  liveBalance\n  isManual\n  balance\n  subType\n  itemId\n  limit\n  color\n  name\n  type\n  mask\n  id\n}";

// ─── Queries ───

export const TRANSACTIONS = "query Transactions($first: Int, $after: String, $last: Int, $before: String, $filter: TransactionFilter, $sort: [TransactionSort!]) {\n  transactions(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    filter: $filter\n    sort: $sort\n  ) {\n    ...TransactionPaginationFields\n    __typename\n  }\n}\n\nfragment TagFields on Tag {\n  colorName\n  name\n  id\n  __typename\n}\n\nfragment GoalFields on Goal {\n  name\n  icon {\n    ... on EmojiUnicode {\n      unicode\n      __typename\n    }\n    ... on Genmoji {\n      id\n      src\n      __typename\n    }\n    __typename\n  }\n  id\n  __typename\n}\n\nfragment TransactionFields on Transaction {\n  suggestedCategoryIds\n  recurringId\n  parentId\n  isoCurrencyCode\n  categoryId\n  isReviewed\n  accountId\n  createdAt\n  isPending\n  tipAmount\n  userNotes\n  itemId\n  amount\n  date\n  name\n  type\n  id\n  tags {\n    ...TagFields\n    __typename\n  }\n  goal {\n    ...GoalFields\n    __typename\n  }\n  __typename\n}\n\nfragment TransactionPaginationFields on TransactionPagination {\n  edges {\n    cursor\n    node {\n      ...TransactionFields\n      __typename\n    }\n    __typename\n  }\n  pageInfo {\n    endCursor\n    hasNextPage\n    hasPreviousPage\n    startCursor\n    __typename\n  }\n  __typename\n}";

export const ACCOUNTS = "query Accounts($filter: AccountFilter, $accountLink: Boolean = false) {\n  accounts(filter: $filter) {\n    ...AccountFields\n    accountLink @include(if: $accountLink) {\n      type\n      account {\n        ...AccountFields\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment AccountFields on Account {\n  hasHistoricalUpdates\n  latestBalanceUpdate\n  hasLiveBalance\n  institutionId\n  isUserHidden\n  isUserClosed\n  liveBalance\n  isManual\n  balance\n  subType\n  itemId\n  limit\n  color\n  name\n  type\n  mask\n  id\n  __typename\n}";

export const CATEGORIES = "query Categories($spend: Boolean = false, $budget: Boolean = false, $rollovers: Boolean) {\n  categories {\n    ...CategoryFields\n    spend @include(if: $spend) {\n      ...SpendFields\n      __typename\n    }\n    budget(isRolloverEnabled: $rollovers) @include(if: $budget) {\n      ...BudgetFields\n      __typename\n    }\n    childCategories {\n      ...CategoryFields\n      spend @include(if: $spend) {\n        ...SpendFields\n        __typename\n      }\n      budget(isRolloverEnabled: $rollovers) @include(if: $budget) {\n        ...BudgetFields\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment SpendMonthlyFields on CategoryMonthlySpent {\n  unpaidRecurringAmount\n  paidRecurringAmount\n  comparisonAmount\n  amount\n  month\n  id\n  __typename\n}\n\nfragment BudgetMonthlyFields on CategoryMonthlyBudget {\n  unassignedRolloverAmount\n  childRolloverAmount\n  unassignedAmount\n  resolvedAmount\n  rolloverAmount\n  childAmount\n  goalAmount\n  amount\n  month\n  id\n  __typename\n}\n\nfragment CategoryFields on Category {\n  isRolloverDisabled\n  canBeDeleted\n  isExcluded\n  templateId\n  colorName\n  icon {\n    ... on EmojiUnicode {\n      unicode\n      __typename\n    }\n    ... on Genmoji {\n      id\n      src\n      __typename\n    }\n    __typename\n  }\n  name\n  id\n  __typename\n}\n\nfragment SpendFields on CategorySpend {\n  current {\n    ...SpendMonthlyFields\n    __typename\n  }\n  histories {\n    ...SpendMonthlyFields\n    __typename\n  }\n  __typename\n}\n\nfragment BudgetFields on CategoryBudget {\n  current {\n    ...BudgetMonthlyFields\n    __typename\n  }\n  histories {\n    ...BudgetMonthlyFields\n    __typename\n  }\n  __typename\n}";

export const TAGS = "query Tags {\n  tags {\n    ...TagFields\n    __typename\n  }\n}\n\nfragment TagFields on Tag {\n  colorName\n  name\n  id\n  __typename\n}";

export const RECURRINGS = "query Recurrings($filter: RecurringFilter) {\n  recurrings(filter: $filter) {\n    ...RecurringFields\n    rule {\n      ...RecurringRuleFields\n      __typename\n    }\n    payments {\n      ...RecurringPaymentFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment RecurringFields on Recurring {\n  nextPaymentAmount\n  nextPaymentDate\n  categoryId\n  frequency\n  emoji\n  icon {\n    ... on EmojiUnicode {\n      unicode\n      __typename\n    }\n    ... on Genmoji {\n      id\n      src\n      __typename\n    }\n    __typename\n  }\n  state\n  name\n  id\n  __typename\n}\n\nfragment RecurringRuleFields on RecurringRule {\n  nameContains\n  minAmount\n  maxAmount\n  days\n  __typename\n}\n\nfragment RecurringPaymentFields on RecurringPayment {\n  amount\n  isPaid\n  date\n  __typename\n}";

export const USER = "query User {\n  user {\n    ...UserFields\n    __typename\n  }\n}\n\nfragment OnboardingFields on Onboarding {\n  lastCompletedStep\n  isCompleted\n  __typename\n}\n\nfragment UserFields on User {\n  budgetingConfig {\n    isEnabled\n    rolloversConfig {\n      isEnabled\n      startDate\n      categories {\n        isRolloverDisabled\n        canBeDeleted\n        isExcluded\n        colorName\n        name\n        id\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  onboarding {\n    ...OnboardingFields\n    __typename\n  }\n  intercomUserHash\n  serviceEndsOn\n  termsStatus\n  id\n  __typename\n}";

export const NETWORTH = "query Networth($timeFrame: TimeFrame) {\n  networthHistory(timeFrame: $timeFrame) {\n    ...NetworthFields\n    __typename\n  }\n}\n\nfragment NetworthFields on NetworthHistory {\n  assets\n  date\n  debt\n  __typename\n}";

export const UPCOMING_RECURRINGS = "query UpcomingRecurrings {\n  unpaidUpcomingRecurrings {\n    ...RecurringFields\n    rule {\n      ...RecurringRuleFields\n      __typename\n    }\n    payments @connection(key: \"upcoming\") {\n      ...RecurringPaymentFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment RecurringFields on Recurring {\n  nextPaymentAmount\n  nextPaymentDate\n  categoryId\n  frequency\n  emoji\n  icon {\n    ... on EmojiUnicode {\n      unicode\n      __typename\n    }\n    ... on Genmoji {\n      id\n      src\n      __typename\n    }\n    __typename\n  }\n  state\n  name\n  id\n  __typename\n}\n\nfragment RecurringRuleFields on RecurringRule {\n  nameContains\n  minAmount\n  maxAmount\n  days\n  __typename\n}\n\nfragment RecurringPaymentFields on RecurringPayment {\n  amount\n  isPaid\n  date\n  __typename\n}";

export const MONTHLY_SPEND = "query MonthlySpend {\n  monthlySpending {\n    comparisonAmount\n    totalAmount\n    date\n    id\n    __typename\n  }\n}";
